# Generated by Django 6.0.2 on 2026-04-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_brand_product_category_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='return_policy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_policy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
