# Generated by Django 6.0.2 on 2026-04-18 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_callsignal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='is_read',
            new_name='seen',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='body',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
    ]
