# Generated by Django 6.0.2 on 2026-04-18 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_blockeduser_voicemessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_user', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(default='User Report', max_length=200)),
                ('body', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
