# Generated by Django 6.0.2 on 2026-04-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_admin_deactivated',
            field=models.BooleanField(default=False),
        ),
    ]
