# Generated by Django 6.0.2 on 2026-04-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_product_is_admin_deactivated'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='privacy_policy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
