# Generated by Django 6.0.2 on 2026-04-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_product_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='warranty_policy',
        ),
        migrations.AddField(
            model_name='product',
            name='has_warranty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
