# Generated by Django 6.0.2 on 2026-04-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_product_warranty_policy_product_has_warranty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_warranty',
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_type',
            field=models.CharField(default='No Warranty', max_length=100),
        ),
    ]
