# Generated by Django 6.0.2 on 2026-04-26 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_product_has_warranty_product_warranty_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='privacy_policy',
            new_name='warranty_policy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='country',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warranty_period',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warranty_type',
        ),
    ]
