# Generated by Django 6.0.2 on 2026-04-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_rename_privacy_policy_product_warranty_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleraccount',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='bank_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='business_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='iban',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='id_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='seller_type',
            field=models.CharField(default='personal', max_length=50),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='tax_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
