# Generated by Django 6.0.2 on 2026-04-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_selleraccount_bank_branch_selleraccount_bank_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleraccount',
            name='country',
            field=models.CharField(blank=True, default='Pakistan', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
