# Generated by Django 6.0.2 on 2026-05-02 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_selleraccount_country_selleraccount_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selleraccount',
            name='country',
        ),
        migrations.RemoveField(
            model_name='selleraccount',
            name='province',
        ),
    ]
